### ISSUE TITLE
setting SERVER_ADDITIONAL_PARAMETERS has no effect

### ISSUE THREAD

**Issue by lucas2350d** [jusito/docker-ttt#17]
Hey justito, i need the -allowlocalhttp flag for a Discord Muter. At the startup im set the ENV var like this:  
-e SERVER_ADDITIONAL_PARAMETERS="-disableluarefresh -allowlocalhttp" \
is it possible to see if that worked? I have a problem with the Discord Muter that points to it

Thanks!

**Comment by jusito** [comment]
1. its set in https://github.com/jusito/docker-ttt/blob/master/gmod/common.cfg#L29
2. which is used here: https://github.com/jusito/docker-ttt/blob/master/gmod/common.cfg#L39
3. So I would expect: `docker exec -it CONTAINER details` should show all startup arguments, including your args.

**Comment by lucas2350d** [comment]
Im set it in the ENV var in Portainer but in the docker details it isnt shown
![image](https://user-images.githubusercontent.com/69628182/222202565-25d38d77-295d-458d-b92a-7ae67e709858.png)

![image](https://user-images.githubusercontent.com/69628182/222202696-c809a733-ae79-475d-88ba-53deaedf607c.png)

**Comment by jusito** [comment]
got it
![image](https://user-images.githubusercontent.com/17811819/222212525-c3c27e91-abe3-4e51-a0a0-6904a25f9699.png)

Upstream changed startparameter handling, initial it was a function now its a variable.
Lgsm config works by providing a _default.cfg and I added a slightly modified common.cfg for environment variables to config. Every value in common.cfg will overwrite _default.cfg, but because of the change I didn't overwrite it. If you dont build it yourself docker hub will take its time, looks fixed for me:

![image](https://user-images.githubusercontent.com/17811819/222213072-5db2616f-679c-41b0-8775-13338549248c.png)

**Comment by lucas2350d** [comment]
Thanks!
