### ISSUE TITLE
Random Shutdown during compose up?

### ISSUE THREAD

**Issue by datashard** [jusito/docker-ttt#19]
Hey, so I'm using a semi-modified version of the compose file in the root of this Project, but when the scripts get to `[forceWorkshopDownload.sh]processing workshop collection` it will just exit with a code of 1

**Comment by jusito** [comment]
Hey, is the workshop collection public?
It would be helpful if you could provide a debug log, e.g. set environment variable DEBUGGING=true, this will enable xtrace in every script. Because every command is printed before execution, the last printed command is the failing one.

**Comment by datashard** [comment]
Ah, I have that set to `Friends Only` currently, I'll test it in a bit with a Public Collection

**Comment by datashard** [comment]
Yeah that seemed to be the issue with this, but I now can't seem to connect to it.

Do I have to pass anything to accept things through specific ips or something?

**Comment by jusito** [comment]
Default ip config is fine. Without seeing your actual configuration, does your configuration pays attention to this?
> Pick your ports `-e SERVER_PORT=27015 -p 27015:27015/udp` both are always needed

The old engine doesn't like virtual mapping like `-e SERVER_PORT=27015 -p 27016:27015/udp`, so if you want it to run on 27016 you need `-e SERVER_PORT=27016 -p 27016:27016/udp`

**Comment by datashard** [comment]
I have it set up like this 

![image](https://pogge.rs/i/uhr.png)

**Comment by jusito** [comment]
1. Port config looks fine.
2. Btw autoload will not work if the mods are in the linked collection. Here is an example how the collection need to look like for autoload: https://steamcommunity.com/workshop/filedetails/?id=1895900191 Maybe you don't want it, just for your information.
3. I would check the server console, often the map name has a suffix or changed after an update, because of that the default map isnt available and the server will not boot. Or server just needs a long time for initial downloading. You can check with `docker exec -it CONTAINER console`

**Comment by jusito** [comment]
Heyho, was you able to look further into this?

**Comment by datashard** [comment]
Ah sorry, yeah. I had the collection set to friends only, it ran fine after.


Time to put together a pack :D
