### ISSUE TITLE
Docker Container always crash

### ISSUE THREAD

**Issue by GrilleGustav** [jusito/docker-ttt#4]
When I start the container with:

```
sudo docker run -d \
 -p 27015:27015/udp \
 -e SERVER_PORT=27015 \
 -e INSTALL_CSS=true \
 -e SERVER_NAME="Skill0rzTTTServer" \
 -e SERVER_PASSWORD="somepw" \
 -e SERVER_DEFAULT_MAP="ttt_lttp_kakariko_a4" \
 -v TTTDev:/home/steam/serverfiles \
 -p 27015:27015/tcp \
 -e SERVER_RCON_PASSWORD="somepw" \
 --name "Skill0rzTTTServer" \
 jusito/docker-ttt:latest
```

The container always crashes with an error message:

```
[prepareServer.sh]check configurations
[initConfig.sh]Request for replacing hostname to hostname "Skill0rzTTTServer", source is found 1 times
sed: -e expression #1, char 68: Invalid preceding regular expression
```

What can we do to fix it?

**Comment by jusito** [comment]
1. are you sure you are using the latest version?
2. if yes you can use as a quick workaround to remove hostname from the file itself and restart container. I would just `docker run -it --rm -v TTTDev:/home alpine:latest` and remove the one line. If my documentation is up to date: /home[/serverfiles]/garrysmod/cfg/gmodserver.cfg 

Tried it on a fresh server and it doesn't crash there, but maybe its because you had a value which i didn't expect there.
```
[entrypoint.sh]update / installation done!
[prepareServer.sh]check configurations
[initConfig.sh]Request for replacing hostname to hostname "Skill0rzTTTServer", source is found 1 times
[initConfig.sh]Request for replacing sv_password to sv_password "somepw", source is found 1 times
[initConfig.sh]Request for replacing rcon_password to rcon_password "somepw", source is found 1 times
[initConfig.sh]Request for replacing sv_voiceenable to sv_voiceenable "1", source is found 1 times
[prepareServer.sh]force workshop download
[forceWorkshopDownload.sh]No auto workshop download
[prepareServer.sh]install & mount gamefiles
[installAndMountAddons.sh]installing & mounting css
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. Intern
```

`sed 's/\\/\\\\/g'` this one cant fail because of this, but this could [sed -i "s/$source/$target/g" "${CFG_PATH}"](https://github.com/jusito/docker-ttt/blob/master/gmod/initConfig.sh#L24).  Should use another method to replace it, because if the existing entry or the new entry has a sed special character, this will probably fail, like in your case.

**Comment by GrilleGustav** [comment]
I will install a fresh system and test it too.

**Comment by jusito** [comment]
btw if you want a very verbose debug output, start the container with `-e DEBUGGING=true ` because this will set in every script `set -o xtrace`

**Comment by jusito** [comment]
Added a patch to delete the line and append a new line, because with this it doesn't depend on input or existing entry value.
Tags are: gmod_ttt_debian-develop oder latest-develop

**Comment by jusito** [comment]
Because I couldn't reproduce this, added a possible bug fix and there wasn't any feedback after Iam assuming its fixed or no longer important.
